Fabrica.o: Clases/Fabrica.cpp 
	g++ Clases/Fabrica.cpp -o Fabrica.o

Funcion.o: Clases/Funcion.cpp
	g++ Clases/Funcion.cpp -o Funcion.o

Pelicula.o: Clases/Pelicula.cpp
	g++ Clases/Pelicula.cpp -o Pelicula.o

Puntaje.o: Clases/Puntaje.cpp
	g++ Clases/Puntaje.cpp -o Puntaje.o

Reloj.o: Clases/Reloj.cpp
	g++ Clases/Reloj.cpp -o Reloj.o

Reserva.o: Clases/Reserva.cpp
	g++ Clases/Reserva.cpp -o Reserva.o

Sala.o: Clases/Sala.cpp
	g++ Clases/Sala.cpp -o Sala.o

Sesion.o: Clases/Sesion.cpp
	g++ Clases/Sesion.cpp -o Sesion.o

Usuario.o: Clases/Usuario.cpp
	g++ Clases/Usuario.cpp -o Usuario.o




CtrAltaCine.o: Clases/CtrAltaCine.cpp
	g++ Cotroladores/CtrAltaCine.cpp -o CtrAltaCine.o

CtrAltaFuncion.o: Clases/CtrAltaFuncion.cpp
	g++ Cotroladores/CtrAltaFuncion.cpp -o CtrAltaFuncion.o

CtrComentarPelicula.o: Clases/CtrComentarPelicula.cpp
	g++ Cotroladores/CtrComentarPelicula.cpp -o CtrComentarPelicula.o

CtrCrearReserva.o: Clases/CtrCrearReserva.cpp
	g++ Cotroladores/CtrCrearReserva.cpp -o CtrCrearReserva.o

CtrEliminarPelicula.o: Clases/CtrEliminarPelicula.cpp
	g++ Cotroladores/CtrEliminarPelicula.cpp -o CtrEliminarPelicula.o

CtrIniciarSesion.o: Clases/CtrIniciarSesion.cpp
	g++ Cotroladores/CtrIniciarSesion.cpp -o CtrIniciarSesion.o

CtrPuntuarPelicula.o: Clases/CtrPuntuarPelicula.cpp
	g++ Cotroladores/CtrPuntuarPelicula.cpp -o CtrPuntuarPelicula.o

CtrReloj.o: Clases/CtrReloj.cpp
	g++ Cotroladores/CtrReloj.cpp -o CtrReloj.o

CtrVerComentarioYPuntaje.o: Clases/CtrVerComentarioYPuntaje.cpp
	g++ Cotroladores/CtrVerComentarioYPuntaje.cpp -o CtrVerComentarioYPuntaje.o

CtrVerinfoPelicula.o: Clases/CtrVerinfoPelicula.cpp
	g++ Cotroladores/CtrVerinfoPelicula.cpp -o CtrVerinfoPelicula.o

IctrAltaCine.o: Interfaces/IctrAltaCine.h
	g++ Interfaces/IctrAltaCine.cpp -o IctrAltaCine.o
IctrAltaFuncion.o: Interfaces/IctrAltaFuncion.h
IctrComentarPelicula.o: Interfaces/IctrComentarPelicula.h
IctrCrearReserva.o: Interfaces/IctrCrearReserva.h
IctrEliminarPelicula.o: Interfaces/IctrEliminarPelicula.h
IctrInicioSesion.o: Interfaces/IctrInicioSesion.h
IctrPuntuarPelicula.o: Interfaces/IctrPuntuarPelicula.h
IctrReloj.o: Interfaces/IctrReloj.h
IctrVerComentarioYPuntaje.o: Interfaces/IctrVerComentarioYPuntaje.h
IctrVerinfoPelicula.o: Interfaces/IctrVerinfoPelicula.h

dtCine.o: Clases/dtCine.cpp
	g++ Dtypes/dtCine.cpp -o dtCine.o

dtComentario.o: Clases/dtComentario.cpp
	g++ Dtypes/dtComentario.cpp -o dtComentario.o

dtDireccion.o: Clases/dtDireccion.cpp
	g++ Dtypes/dtDireccion.cpp -o dtDireccion.o

dtFecha.o: Clases/dtFecha.cpp
	g++ Dtypes/dtFecha.cpp -o dtFecha.o

dtFuncion.o: Clases/dtFuncion.cpp
	g++ Dtypes/dtFuncion.cpp -o dtFuncion.o

dtHora.o: Clases/dtHora.cpp
	g++ Dtypes/dtHora.cpp -o dtHora.o

dtHorario.o: Clases/dtHorario.cpp
	g++ Dtypes/dtHorario.cpp -o dtHorario.o

dtInfoPelicula.o: Clases/dtInfoPelicula.cpp
	g++ Dtypes/dtInfoPelicula.cpp -o dtInfoPelicula.o

dtPeliculaCompleto.o: Clases/dtPeliculaCompleto.cpp
	g++ Dtypes/dtPeliculaCompleto.cpp -o dtPeliculaCompleto.o

dtPelicula.o: Clases/dtPelicula.cpp
	g++ Dtypes/dtPelicula.cpp -o dtPelicula.o

dtPuntaje.o: Clases/dtPuntaje.cpp
	g++ Dtypes/dtPuntaje.cpp -o dtPuntaje.o

dtReloj.o: Clases/dtReloj.cpp
	g++ Dtypes/dtReloj.cpp -o dtReloj.o

dtSala.o: Clases/dtSala.cpp
	g++ Dtypes/dtSala.cpp -o dtSala.o

dtTarjetas.o: Clases/dtTarjetas.cpp
	g++ Dtypes/dtTarjetas.cpp -o dtTarjetas.o

ManejadorCine.o: Clases/ManejadorCine.cpp
	g++ Manejador/ManejadorCine.cpp -o ManejadorCine.o

ManejadorCrearReserva.o: Clases/ManejadorCrearReserva.cpp
	g++ Manejador/ManejadorCrearReserva.cpp -o ManejadorCrearReserva.o

ManejadorFunciones.o: Clases/ManejadorFunciones.cpp
	g++ Manejador/ManejadorFunciones.cpp -o ManejadorFunciones.o

ManejadorPelicula.o: Clases/ManejadorPelicula.cpp
	g++ Manejador/ManejadorPelicula.cpp -o ManejadorPelicula.o

ManejadorUsuario.o: Clases/ManejadorUsuario.cpp
	g++ Manejador/ManejadorUsuario.cpp -o ManejadorUsuario.o

ui.o: Clases/ui.cpp
	g++ UI/ui.cpp -o ui.o
